---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.haml"
  - "**.rb"
  - "**.js"
exclude_paths:
- config/
- db/
- features/
- lib/tasks/cucumber.rake
- script/
- spec/
- vendor/
